-- Explicit mutation catalog. Reads, feed polling, upload chunks and secrets are
-- deliberately excluded. Request fields are an allowlist, not the raw NUI body.
SkyPhoneLog.Actions = {}
local actions = SkyPhoneLog.Actions

local function add(category, app, status, names, fields, include_result)
    for name in names:gmatch("%S+") do
        actions[app .. ":" .. name] = {
            category = category, status = status, fields = fields or "", result = include_result,
        }
    end
end

local function toggle(field, enabled, disabled)
    return function(data) return data[field] and enabled or disabled end
end

local function state(field)
    return function(data) return tostring(data[field] or "changed") end
end

local social_profile = "handle username displayName bio avatarId avatarMediaId private accountType"
local social_post = "id body caption location mediaId mediaIds mediaType commentsEnabled replyToId quoteId parentId"
for app, category in pairs({ picstagram = "Picstagram", fliptok = "FlipTok", feather = "Feather" }) do
    add(category, app, "created", "register create-profile", social_profile)
    add(category, app, "logged_in", "login", "handle", false)
    add(category, app, "logged_out", "logout", "", false)
    add(category, app, "edited", "update-profile", social_profile)
    add(category, app, toggle("active", "added", "removed"), "react comment-react follow", "id profileId kind active")
    add(category, app, "reported", "report", "id reason details targetId targetType")
    add(category, app, "read", "mark-activities", "", false)
end
add("Picstagram", "picstagram", "created", "publish-post publish-story comment", social_post)
add("Picstagram", "picstagram", "edited", "update-post", social_post)
add("Picstagram", "picstagram", state("status"), "set-post-status", "id status")
add("Picstagram", "picstagram", "deleted", "remove-comment remove-story", "id")
add("Picstagram", "picstagram", "viewed", "view-story", "id", false)
add("Picstagram", "picstagram", toggle("accept", "accepted", "declined"), "respond-follow", "profileId accept")
add("Picstagram", "picstagram", toggle("active", "blocked", "unblocked"), "block", "profileId active")
add("Picstagram", "picstagram", state("action"), "admin-resolve-report", "id action")
add("FlipTok", "fliptok", toggle("draft", "draft_created", "published"), "publish",
    social_post .. " draft visibility trimStartMs trimEndMs coverTimeMs musicTrack customMusicUrl musicVolume originalVolume")
add("FlipTok", "fliptok", "created", "comment", social_post)
add("FlipTok", "fliptok", "deleted", "delete", "id")
add("FlipTok", "fliptok", "blocked", "block", "profileId")
add("FlipTok", "fliptok", "viewed", "view", "id", false)
add("FlipTok", "fliptok", "shared", "share", "id", false)
add("Feather", "feather", "created", "create-post", social_post)
add("Feather", "feather", "deleted", "delete", "id")
add("Feather", "feather", "removed", "remove-connection", "profileId mode")
add("Feather", "feather", "blocked", "block", "profileId")

-- Registers automatically when feat/skypic is merged; no dependency on SkyPic
-- tables or callbacks exists until that app is actually loaded and used.
local skypic_profile = "handle displayName bio avatarMediaId avatarSeed storyPrivacy showInQuickAdd allowStoryReplies"
local skypic_media = "mediaId mediaIds mediaType caption textOverlay overlayColor durationSeconds allowReplay recipientIds"
add("SkyPic", "skypic", "created", "create-profile", skypic_profile)
add("SkyPic", "skypic", "edited", "update-profile", skypic_profile)
add("SkyPic", "skypic", "deleted", "delete-account", "confirmed", false)
add("SkyPic", "skypic", "requested", "add-friend", "profileId")
add("SkyPic", "skypic", toggle("accept", "accepted", "declined"), "respond-friend", "friendshipId accept")
add("SkyPic", "skypic", "removed", "remove-friend", "friendshipId profileId")
add("SkyPic", "skypic", toggle("blocked", "blocked", "unblocked"), "block", "profileId blocked")
add("SkyPic", "skypic", "sent", "send-message", "friendshipId body")
add("SkyPic", "skypic", "read", "mark-thread", "friendshipId", false)
add("SkyPic", "skypic", toggle("saved", "saved", "unsaved"), "save-message", "messageId saved")
add("SkyPic", "skypic", toggle("forEveryone", "deleted_for_everyone", "deleted_for_self"), "delete-message", "messageId forEveryone")
add("SkyPic", "skypic", "sent", "send-snap", skypic_media)
add("SkyPic", "skypic", "opened", "open-snap", "snapId")
add("SkyPic", "skypic", "replayed", "replay-snap", "snapId")
add("SkyPic", "skypic", "published", "publish-story", skypic_media)
add("SkyPic", "skypic", "viewed", "view-story", "storyId", false)
add("SkyPic", "skypic", "deleted", "remove-story", "storyId")
add("SkyPic", "skypic", "published", "publish-spotlight", skypic_media .. " isSponsored adHeadline commentsEnabled")
add("SkyPic", "skypic", "viewed", "view-spotlight", "spotlightId", false)
add("SkyPic", "skypic", toggle("active", "liked", "unliked"), "like-spotlight", "spotlightId active")
add("SkyPic", "skypic", "created", "comment-spotlight", "spotlightId body")
add("SkyPic", "skypic", "deleted", "delete-spotlight-comment", "commentId")
add("SkyPic", "skypic", "deleted", "remove-spotlight", "spotlightId")
add("SkyPic", "skypic", "reported", "report-spotlight", "spotlightId reason details")

add("Messages", "messages", "sent", "send", "phoneNumber body messageType mediaAssetId contactId sharePayload mediaMime mediaDurationMs")
add("Messages", "messages", "deleted", "delete", "phoneNumbers")
add("Messages", "messages", "read", "thread", "phoneNumber", false)
add("Contacts", "contacts", toggle("id", "edited", "created"), "save", "id name phoneNumber email organization notes avatarMediaId")
add("Contacts", "contacts", toggle("favorite", "favorited", "unfavorited"), "favorite", "id favorite")
add("Contacts", "contacts", "deleted", "delete", "id")
-- Call lifecycle is recorded inside calls.lua, including timers and server APIs.
add("Calls", "calls", "blocked", "block", "phoneNumber")
add("Calls", "calls", toggle("enabled", "enabled", "disabled"), "set-speaker", "id enabled")
add("Calls", "calls", toggle("enabled", "muted", "unmuted"), "set-muted", "id enabled")

add("DarkChat", "darkchat", "created", "create-profile", "")
add("DarkChat", "darkchat", "deleted", "delete-profile", "", false)
add("DarkChat", "darkchat", "edited", "update-profile", "alias notificationMode activityVisible")
add("DarkChat", "darkchat", "started", "start", "identifier")
add("DarkChat", "darkchat", "sent", "send", "conversationId body messageType mediaAssetId replyToId sharePayload mediaMime mediaDurationMs")
add("DarkChat", "darkchat", "reacted", "react", "messageId reaction")
add("DarkChat", "darkchat", state("action"), "message-action", "messageId action")
add("DarkChat", "darkchat", "edited", "update-conversation", "conversationId disappearingSeconds notificationsEnabled readReceipts")
add("DarkChat", "darkchat", "added", "add-contact", "conversationId alias")
add("DarkChat", "darkchat", "removed", "remove-contact", "conversationId")
add("DarkChat", "darkchat", toggle("blocked", "blocked", "unblocked"), "block", "conversationId blocked")
add("DarkChat", "darkchat", "reported", "report", "conversationId messageId reason details")
add("DarkChat", "darkchat", "cleared", "clear", "conversationId")
add("DarkChat", "darkchat", "read", "thread", "conversationId", false)
add("Flare", "flare", "deleted", "delete-profile", "", false)
add("Flare", "flare", "saved", "save-profile",
    "name age bio gender interestedIn minAge maxAge avatar interests lookingFor photoMediaIds", false)
add("Flare", "flare", toggle("enabled", "enabled", "disabled"), "set-discovery", "enabled", false)
add("Flare", "flare", state("choice"), "swipe", "targetId choice", false)
add("Flare", "flare", "rewound", "rewind", "", false)
add("Flare", "flare", "unmatched", "unmatch", "matchId", false)
add("Flare", "flare", "sent", "send", "matchId body messageType mediaId mediaAssetId sharePayload")
add("Flare", "flare", "read", "thread", "matchId", false)

for app, category in pairs({ account = "Account", mail = "Mail", crypto = "Crypto", crewlink = "CrewLink" }) do
    add(category, app, "registered", "register", "email handle username", false)
    add(category, app, "logged_in", "login", "email handle username", false)
    add(category, app, "logged_out", "logout", "", false)
end
add("Account", "account", "removed", "remove-device", "imei")
add("Mail", "mail", "created", "create-mailbox", "name")
add("Mail", "mail", "deleted", "delete-mailbox delete-draft delete-forever delete-many", "id ids folder")
actions["mail:delete-many"].status = function(data)
    return (data.folder == "drafts" or data.folder == "trash") and "deleted" or "trashed"
end
add("Mail", "mail", "saved", "save-draft", "id recipients subject body")
add("Mail", "mail", "sent", "send", "recipients subject body draftId")
add("Mail", "mail", toggle("read", "read", "unread"), "set-read", "id read")
add("Mail", "mail", "read", "get", "id", false)
add("Mail", "mail", "moved", "move", "id mailboxId")
add("Mail", "mail", "trashed", "trash", "id")
add("Mail", "mail", "restored", "restore", "id")
add("Mail", "mail", "deleted", "empty-trash", "")

add("Marketplace", "marketplace", state("mode"), "auth", "mode avatarMediaId", false)
add("Marketplace", "marketplace", "edited", "profile-save", "avatarMediaId bio displayName showPhone")
local listing = "id revision title description category district condition price priceType images showPhone"
add("Marketplace", "marketplace", "created", "create", listing)
add("Marketplace", "marketplace", "edited", "update", listing)
add("Marketplace", "marketplace", state("status"), "set-status", "id status inquiryId")
add("Marketplace", "marketplace", toggle("favorite", "favorited", "unfavorited"), "favorite", "id favorite")
add("Marketplace", "marketplace", "sent", "send-message", "inquiryId listingId body")
add("Marketplace", "marketplace", "read", "get-inquiry", "id", false)
add("Marketplace", "marketplace", "offered", "make-offer", "inquiryId amount")
add("Marketplace", "marketplace", state("action"), "respond-offer", "inquiryId action")
add("Marketplace", "marketplace", "reported", "report", "id reason details")
add("Marketplace", "marketplace", toggle("blocked", "blocked", "unblocked"), "block", "listingId blocked")
add("Pages", "pages", "edited", "profile-save", "handle bio avatarMediaId")
add("Pages", "pages", "created", "create", "title body category district images")
add("Pages", "pages", "shared", "share-citymarkt", "listingId")
add("Pages", "pages", toggle("active", "added", "removed"), "react", "id kind active")
add("Pages", "pages", "deleted", "delete", "id")

add("Companies", "companies", "created", "create-request", "companyId serviceId subject description mediaIds")
add("Companies", "companies", "cancelled", "cancel-request", "requestId revision")
add("Companies", "companies", "sent", "send-message", "requestId revision body")
add("Companies", "companies", "claimed", "claim-request", "requestId revision")
add("Companies", "companies", "assigned", "assign-request", "requestId revision memberId")
add("Companies", "companies", state("status"), "update-request-status", "requestId revision status")
add("Companies", "companies", "edited", "update-availability update-profile update-hours update-services",
    "revision availability expiresAt acceptsRequests address coords description district locationLabel phoneNumber logoMediaId logoUrl coverMediaId coverUrl hours services")
add("Companies", "companies", "published", "publish-announcement", "revision body expiresAt")
add("Companies", "companies", "changed", "set-call-availability", "available companyId")
add("Banking", "banking", "transferred", "transfer", "amount phoneNumber")
add("Crypto", "crypto", "edited", "update-profile", "handle hideBalances priceAlerts tradeConfirmations", false)
add("Crypto", "crypto", "transferred", "transfer", "walletKey marketId quantity idempotencyKey")
add("Crypto", "crypto", "executed", "execute", "quoteId idempotencyKey")
add("Crypto", "crypto", "deposited", "deposit", "amount idempotencyKey")
add("Crypto", "crypto", "withdrawn", "withdraw", "amount idempotencyKey")
add("Billing", "billing", "read", "markRead", "id")
add("Billing", "billing", "disputed", "dispute", "id")
add("Billing", "billing", "paid", "pay", "id")

add("Gallery", "gallery", toggle("favorite", "favorited", "unfavorited"), "favorite", "id favorite")
add("Uploads", "media:import", "imported", "commit url", "sourceId externalIds mediaType url")
add("Memos", "memos", "edited", "update", "id title note pinned revision")
add("Memos", "memos", "deleted", "delete", "id")
add("Notes", "notes", "created", "create", "id title body pinned")
add("Notes", "notes", "edited", "update", "id title body pinned revision")
add("Notes", "notes", "deleted", "delete", "id")
add("Calendar", "calendar", "created", "create", "title note startsAt endsAt reminderMinutes")
add("Calendar", "calendar", "edited", "update", "id revision title note startsAt endsAt reminderMinutes")
add("Calendar", "calendar", "deleted", "delete", "id")
add("WeazelNews", "weazel-news", "created", "create", "title body category status imageMediaId imageMediaIds")
add("WeazelNews", "weazel-news", "edited", "update", "id revision title body category status imageMediaId imageMediaIds")
add("WeazelNews", "weazel-news", "deleted", "delete", "id revision")
add("CityWarn", "citywarn", "published", "publish", "area body category durationMinutes instructions severity title")
add("CityWarn", "citywarn", "edited", "update", "id revision message")
add("CityWarn", "citywarn", "resolved", "resolve", "id revision message")

local crew = "groupId profileId name username colour avatarMediaId allowMemberPings overheadAllowed mapVisible overheadVisible"
add("CrewLink", "crewlink", "edited", "update-profile update-group", crew)
add("CrewLink", "crewlink", "created", "create-group", crew)
add("CrewLink", "crewlink", "deleted", "delete-group", "groupId", false)
add("CrewLink", "crewlink", "activated", "set-active", "groupId")
add("CrewLink", "crewlink", "joined", "join-code", "", false)
add("CrewLink", "crewlink", "code_rotated", "rotate-code", "groupId", false)
add("CrewLink", "crewlink", "invited", "invite-nearby", "groupId targetSource")
add("CrewLink", "crewlink", toggle("accepted", "accepted", "declined"), "respond-invite", "invitationId accepted")
add("CrewLink", "crewlink", "edited", "update-member", "groupId profileId role")
add("CrewLink", "crewlink", "transferred", "transfer-owner", "groupId profileId")
add("CrewLink", "crewlink", "removed", "remove-member", "groupId profileId")
add("CrewLink", "crewlink", "left", "leave", "groupId", false)
add("CrewLink", "crewlink", "created", "create-ping", "groupId type label coords lifetimeSeconds useCurrent")
add("CrewLink", "crewlink", "deleted", "remove-ping", "groupId pingId")
add("SkyRide", "skyride", "edited", "update-profile", "name avatarMediaId")
add("SkyRide", "skyride", "requested", "request", "quoteId pickup destination customFare")
add("SkyRide", "skyride", toggle("online", "online", "offline"), "set-driver-status", "online")
for name, status in pairs({ accept = "accepted", arrive = "arrived", start = "started", complete = "completed", cancel = "cancelled", rate = "rated" }) do
    add("SkyRide", "skyride", status, name, "rideId reason rating comment tip")
end
add("Radio", "radio", "connected", "connect", "frequency secondaryFrequency")
add("Radio", "radio", "disconnected", "disconnect", "")
add("Radio", "radio", "edited", "set-speaker save-settings save-badge save-display-name", "enabled key value badge displayName")
add("Garage", "garage", "requested", "valet-request", "plate")
add("Garage", "garage", "cancelled", "valet-cancel", "orderId")
add("Garage", "garage", "completed", "valet-complete", "orderId networkId")
add("Housing", "housing", "requested", "prepare", "action")
add("Health", "health", "edited", "save-profile", "bloodType allergies conditions medication emergencyName emergencyPhone emergencyRelation")
add("Music", "music", "added", "add-youtube add-to-playlist", "id title artist url source playlistId songId")
add("Music", "music", "removed", "remove-youtube remove-from-playlist", "id playlistId songId")
add("Music", "music", "created", "create-playlist", "name")
add("Music", "music", "edited", "rename-playlist", "id name")
add("Music", "music", "deleted", "delete-playlist", "id")
add("Map", "map", "created", "create-marker", "label coords color")
add("Map", "map", "deleted", "delete-marker", "id")
add("EasyShare", "easyshare", "edited", "set-visibility", "visibility")
add("EasyShare", "easyshare", "requested", "request", "targetId", false)
add("EasyShare", "easyshare", toggle("accepted", "accepted", "declined"), "respond", "id accepted")
add("EasyShare", "easyshare", "cancelled", "cancel", "id")
add("Device", "device", "saved", "save", "namespace revision", false)
add("Device", "notifications", "saved", "save", "imei", false)
add("Device", "device", "factory_reset", "factory-reset", "imei", false)
add("Security", "security", "unlocked", "unlock", "", false)
add("Security", "security", "passcode_set", "set-passcode", "", false)
add("Security", "security", "passcode_changed", "change-passcode", "", false)
add("Security", "security", "passcode_disabled", "disable-passcode", "", false)
add("Sim", "sim", "inserted", "insert", "imei", false)
add("Sim", "sim", "ejected", "eject", "", false)
add("Admin", "admin", "edited", "save-apps change-number", "source imei changes phoneNumber", false)
add("Admin", "admin", "password_revealed", "reveal-password", "source imei kind", false)
add("Admin", "admin", "passcode_reset", "reset-passcode", "source imei", false)
add("Admin", "admin", "factory_reset", "factory-reset", "source imei", false)
add("Admin", "admin", "configuration_saved", "save-configurator", "revision", false)
add("Admin", "admin", "tone_created", "tone-upload-finish", "id", false)
add("Admin", "admin", "tone_deleted", "delete-tone", "id", false)
add("CustomApps", "custom-app:storage", "saved", "set", "appId key", false)
